[build]
  command = "npm run build"
  functions = "built-lambda"
  publish = "build"

[[redirects]]
  from = "/updateEpisodes"
  to = "/.netlify/functions/updateEpisodes"

[[redirects]]
  from = "/api/getEpisodes"
  to = "/.netlify/functions/getEpisodes"