[build]
  command = "yarn build"
  functions = "built-lambda"
  publish = "build"

[[redirects]]
  from = "/updateEpisodes"
  to = "/.netlify/functions/updateEpisodes"
  from = "/getEpisodes"
  to = "/.netlify/functions/getEpisodes"